name: 'Datadog Github Deployment Metrics Reporter'
description: 'Send Github deployment metrics and events to Datadog'
inputs:
  DD_API_KEY:
    description: 'DataDog API KEY'
    required: true
  BUILD_STATUS:
    description: 'Status of the build (success or failure)'
    required: true
  GITHUB_REPOSITORY:
    description: 'The GitHub repository'
    required: true
  LATEST_BUILD_VERSION:
    description: 'The latest build version'
runs:
  using: 'node16'
  main: 'dist/index.js'
